# 서버 port 설정
server:
  port: 8800
  servlet:
    context-path: /blog
    

# mysql 데이터베이스 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # 프로젝트 재실행할때마다 생성하겟다. 최초에만 create, 추후에는 update로 수정해야함 필수 #
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false #JPA의 넘버링을 따라가지 않겠다.
    show-sql: true #이 부분으로 인해 프로젝트 실행시 테이블 생성 결과를 콘솔창에 띄어줌
    properties:
      hibernate.format_sql: true # 이부분으로 인해 콘솔창에 정렬 하라는 의미임

  jackson:
    serialization:
      fail-on-empty-beans: false